CONNECT TO RBD;

QUIESCE DATABASE IMMEDIATE FORCE CONNECTIONS;
CONNECT RESET;
BACKUP DATABASE RBD TO "D:\BACKUP\BACKUP" WITH 2 BUFFERS BUFFER 1024 PARALLELISM 1 COMPRESS  WITHOUT PROMPTING;
CONNECT TO RBD;
UNQUIESCE DATABASE;

CONNECT RESET;