attach to db2;

drop database RBD;

RESTORE DATABASE RBD FROM "D:\BACKUP\FOND+STRUKTURA+SLOVNUKU" TAKEN AT 20220423193922 TO "D:" INTO RBD WITH 2 BUFFERS BUFFER 1024 PARALLELISM 1 WITHOUT PROMPTING;

detach;